server:
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 200
      min-spare: 30
    connection-timeout: 5000ms
  port: 996
  servlet:
    context-path: /emos-wx-api
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://124.221.192.169:3306/emos?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
      username: root
      password: iflytek
      initial-size: 1
      max-active: 5
      min-idle: 2
      max-wait: 60000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
  mail:
    default-encoding: UTF-8
    host: 
    username: 
    password: 


  redis:
    database: 0
    host: 124.221.192.169
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 1000
        max-wait: -1ms
        max-idle: 16
        min-idle: 8

  data:
    mongodb:
      host: 124.221.192.169
      port: 27017
      database: admin
      authentication-database: admin
      username: emos
      password: emos

  rabbitmq:
    host: 124.221.192.169
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    #listener:
    #  simple:
    #    acknowledge-mode: manual #设置确认模式手工确认
    #    concurrency: 3 #消费者最小数量
    #    max-concurrency: 10 # 消费者最大数量

mybatis:
    mapper-locations: classpath*:mapper/*.xml
    type-aliases-package: com.vincent.emos.wx.db.pojo
    configuration:
      #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
      map-underscore-to-camel-case: true
#logging:
#    level:
#      root: info
#      com.vincent.emos.wx.db.dao: warn
#    pattern:
#      console: "%d{HH:mm:ss}  %-5level  %msg%n"

emos:
  jwt:
    #密钥
    secret: abc123456
    #令牌过期时间（天）
    expire:  5
    #令牌缓存时间（天数）
    cache-expire: 10

 
  mail:
    system: 398305246@qq.com
    hr: 398305246@qq.com

  image-folder: /root/image

#微信参数配置
wx:
  app-id: wx2847538d05e183bd
  app-secret: 93116ab650852efe104c979cc20827d4

###以下参数需要在https://console.cloud.tencent.com/aiface/verify-face/stat 人脸验证控制台查看
tencentcloud:
  secrect-id: AKIDCDxReaFdka8QRBdojNkpeCUVFiupSpvj
  secrect-key: YqqZ1C6i37uQfdKktkLfiUyB7l8E3aqq
  facelib-id: 1000
  facelib-name: 在线办公

# ===================================================================
# 分布式文件系统FDFS配置
# ===================================================================
fdfs:
  so-timeout: 1501
  connect-timeout: 2000
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
    - 124.221.192.169:22122
  path: http://124.221.192.169:8888/
